modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "furnish"
version = "${version}"
displayName = "Furnish"
authors = "MWouink"
description = '''
Adds lovely and useful Furniture to Minecraft
'''
logoFile = "furnish.png"
displayURL="https://wouink.github.io"
credits="Book Pile model from the 'Comfy Cozy' mod (MIT Licensed). Bookshelf Chest textures from 'Charm' mod (MIT Licensed). Brazilian translations by mayrotiem. Chinese translations by Pancakes0228."

[[dependencies.furnish]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.furnish]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.furnish]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "furnish.mixins.json"
